### ISSUE TITLE
CreateThread/ExitThread

### ISSUE THREAD

**Issue by thims** [libyal/libcthreads#2]
Consider using _beginthreadex/_endthreadex if possible: this will prevent issues when using CRT in threads.

**Comment by joachimmetz** [comment]
Not sure these functions seem to come with some limitations.
https://msdn.microsoft.com/en-us/library/kdzttdcb.aspx

**Comment by thims** [comment]
This is all about WRT/Windows Store apps.

**Comment by joachimmetz** [comment]
Not sure what you mean, can you be a bit more verbose?

**Comment by thims** [comment]
There is one limitation: you can't use these functions in Windows Store apps (special kind of Win8/8.1 apps). But you really don't need the library like this in Store Apps.

**Comment by joachimmetz** [comment]
So the following article indicates the only value of using _beginthreadex/_endthreadex is that it handles signal correctly, see: http://support.microsoft.com/en-us/kb/104641/en-us

Since the idea is to use the Visual Studio CRT as little as possible, I don't think it is of any value to use these functions.

**Comment by thims** [comment]
By the way, beginning from VC++ 2015 _beginthreadex keeps reference to thread module that prevents the unloading of the module until the thread execution is finished.
